/// Flutter icons SportsIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SportsIcon
///      fonts:
///       - asset: fonts/SportsIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SportsIcon {
  SportsIcon._();

  static const _kFontFam = 'SportIcons';
  static const String? _kFontPkg = "SportIcons";

  static const IconData adventure_sportive_transport_side_view= IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adventure_sport_silhouettes = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData american_football_ball = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aquatics = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData athlete = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData auto_racing = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badminton_ball = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badminton_player = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badminton = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball_player__1_ = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball_player = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball_player_with_the_ball = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData black_baseball_ball = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData black_tower_chess_piece_shape = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_shoot_on_target_center = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camels_race = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData climbing_silhouette = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData criquet_ball = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cycling = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diver_silhouette__1_ = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell__1_ = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData extreme_skydiving__1_ = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData extreme_skydiving = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData extreme_snowboard_silhouette = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female_boxing_silhouette_of_a_young_woman = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf_player = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hockey_player_silhouette = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hockey = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hunter_hunting_with_bow_and_arrow__1_ = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hunter_hunting_with_bow_and_arrow = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_sports = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jet_boating_sport_silhouette = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jockey_and_horse_in_competition = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mlb = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mma = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moto_racing = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle_traveller_silhouette = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mountain_cycling_cyclist_silhouette = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multisports = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfl = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nhl = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData olympic_curling_player = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paralympic_alpine_skiing_silhouette = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paralympic_cycling = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paralympic_judo__1_ = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paralympic_judo = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paralympic_rowing = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_practicing_kickboxing = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_with_hat_riding_on_a_horse = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ping_pong_silhouettes = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diver_silhouette = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polo_silhouette = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rodeo_silhouette__1_ = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rodeo_silhouette = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rugby = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shooting = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skater_silhouette = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shooting_target = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_field_from_top_view = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snooker = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speed_skiing = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squash = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strong_man_silhouette_with_weight = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData synchronized_swimming_2 = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData synchronized_swimming = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_tennis = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tai_chi_chuan_posture_silhouette = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trail_running_shoe = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_motor_flags = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_persons_fighting_silhouettes = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball_net_with_hand_silhouette = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball_silhouette = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weightlifting_silhouette = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
